services:
  mongodb:
    build: ./mongodb
    image: varunkumarpinnam/mongodb:1.0.0
    container_name: mongodb

  catalogue:
    build: ./catalogue
    image: varunkumarpinnam/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

  user:
    build: ./user
    image: varunkumarpinnam/user:1.0.0
    container_name: user
    depends_on:
    - mongodb
    - redis

  redis:
    image: redis:7.0
    container_name: redis

  cart:
    build: ./cart
    image: varunkumarpinnam/cart:1.0.0
    container_name: cart
    depends_on:
    - catalogue
    - redis

  frontend:
    build: ./frontend
    image: varunkumarpinnam/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    
networks:
  default:
    driver: bridge
    name: roboshop
    external: false
